// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-U3Vqhjmv7dv24frgOcXElXQdyaClos',
    appId: '1:654060244736:web:d428d9b7cef7f3ddf1ade5',
    messagingSenderId: '654060244736',
    projectId: 'worldtalk-ae362',
    authDomain: 'worldtalk-ae362.firebaseapp.com',
    storageBucket: 'worldtalk-ae362.appspot.com',
    measurementId: 'G-3Y78CP282S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeuS9Jd9_12h4oNbF6IpV_JH_S0zE4dA4',
    appId: '1:654060244736:android:882e9722e01ecd0ff1ade5',
    messagingSenderId: '654060244736',
    projectId: 'worldtalk-ae362',
    storageBucket: 'worldtalk-ae362.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa-i-mchOHPq6jJPwaIy2CL1zyjJeIOEE',
    appId: '1:654060244736:ios:256f1ac566e1eab9f1ade5',
    messagingSenderId: '654060244736',
    projectId: 'worldtalk-ae362',
    storageBucket: 'worldtalk-ae362.appspot.com',
    iosBundleId: 'com.example.worldTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa-i-mchOHPq6jJPwaIy2CL1zyjJeIOEE',
    appId: '1:654060244736:ios:abbeb16312d4f72ff1ade5',
    messagingSenderId: '654060244736',
    projectId: 'worldtalk-ae362',
    storageBucket: 'worldtalk-ae362.appspot.com',
    iosBundleId: 'com.example.worldTalk.RunnerTests',
  );
}
